language: python
dist: trusty
sudo: false

python:
    - "3.5"
    - "3.6"
    - "nightly"
    # - "pypy-5.3.1"  # install command doesnt work with pypy, help appreciated

cache: pip

install:
    - pip install .
    - pip install hypothesis

script:
    - pytest --verbose --tb=native

notifications:
    email:
        on_success: change
        on_failure: change
    irc:
        channels:
            - "irc.freenode.net#8banana"
        skip_join: true
        on_success: change
        on_failure: change
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
